### ISSUE TITLE
Kai powers stop at level 50.

### ISSUE THREAD

**Issue by churra** [syntax53/MMUD-Explorer#7] opened 2016-08-07 17:45 UTC
Edited boards may have Kai powers higher than level 50.
I play on a board where the Kai powers go as high as level 225.

**Comment by syntax53** [comment] 2016-08-08 02:55
Have a link to the dats for the board?  There's no hard cap in MME.

**Comment by churra** [comment] 2016-08-08 13:04
The dats are posted in a closed facebook group. I have attached a copy of
the latest version. As you can tell I play on Hated Reality.
I have also tried earlier dats that worked fine before version 8 and the
same thing.

**Comment by syntax53** [comment] 2016-08-08 13:15
I assume you replied via email.  The attachment did not come through.  You can attach on github directly.

**Comment by Prolesious** [comment] 2016-08-08 13:28
I play a ninja - race griffon.
[data-HatedReality.zip](https://github.com/syntax53/MMUD-Explorer/files/406874/data-HatedReality.zip)

**Comment by syntax53** [comment] 2016-08-08 13:31
... these dats are old?  Note the warning when opening it up.

**Comment by Prolesious** [comment] 2016-08-08 13:32
correct.  everything works as intended.

**Comment by syntax53** [comment] 2016-08-08 13:33
heh, no.  The sysop needs to install NMR v1.8.1 and then create new MME dats.

**Comment by syntax53** [comment] 2016-08-08 13:35
I see the dats were created with NMR v1.6.1, which is 10 years old.  Supporting new class spells is one of the main featured of MME v1.8 and it requires dats created with the newest NMR.

**Comment by Prolesious** [comment] 2016-08-08 13:37
I just asked him to export it to confirm.   He's been using the update just
hasn't gave us an update dat

**Comment by Prolesious** [comment] 2016-08-20 23:39
updated dat, and still no kai powers past 50.  for ninja or mystic.
[data-MyBBSName.zip](https://github.com/syntax53/MMUD-Explorer/files/428562/data-MyBBSName.zip)

**Comment by syntax53** [comment] 2016-08-21 03:24
What are the names of the spells?

**Comment by Prolesious** [comment] 2016-08-21 05:25
0   0    bear  way of the bear
  2   1    swan  way of the swan
  3   2     owl  way of the owl
  4   3     cat  way of the cat
  5   3    tige  way of the tiger
  6   4     rat  way of the rat
  7   4    boar  way of the boar
  8   0    swrg  shadow rising
  8   3    drgn  way of the dragon
  9   3    monk  way of the monkey
 10   6    mant  way of the mantis
 12   3    tort  way of the tortoise
 15   4    bear  way of the bear
 16   5    trol  way of the troll
 18   6    cobr  way of the cobra
 21   7    hypn  hypnotic hands
 24   5    fist  way of the exploding fist
 27   8    pres  pressure points
 30   12   hand  hand of death
 33   10   jagr  way of the jaguar
 35   0    fgjk  flying jumpkick
 35   15   puri  purify
 45   0    woma  woman's fury
 50   3    dfrm  form of the dragon
 50   3    sdmr  form of the sacred master
 50   15   lion  way of the lion
 50   10   slph  way of the sliph
 60   5    dove  way of the dove
 75   15   woll  way of the lion
 80   16   gprs  greater pressure points
 90   30   over  way of the overlord
100   20   pure  way of the puritan
100   5    trlc  way of the trolloc

**Comment by syntax53** [comment] 2016-08-21 23:34
fixed in v1.8.1.  had nothing to do with the level.  was just a coincidence that everything from level 50 down was learnable via textblock or casted by other means.

**Closed by syntax53** 2016-08-21 23:34 UTC
Labels: bug
